### GENERAL SETTINGS ###

# Site settings
title: S2E Lab
description: "All about the Security and Software Engineering Lab at the University of Notre Dame!"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://s2e-lab.github.io"
github_username: s2e-lab
github_repo: s2e-lab.github.io

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

include:
  - teaching/sse-book/build/_assets

# ORIGINAL TEMPLATE'S COLORS
# Palette: https://palettes.shecodes.io/palettes/1291
colors:  
  primary: "#407088"
  primary_rgb: "64,112,136" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#233142" 
  link: "#f95959"
  link_hover: "#e3e3e3"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Palette: https://palettes.shecodes.io/palettes/267

# colors:  
#   primary: "#455d7a" 
#   primary_rgb: "236,236,236" #rgb of the primary. Needed in some places for the transparency effect.
#   secondary: "#233142" 
#   link: "#f95959"
#   link_hover: "#e3e3e3"
#   footer_heading: "#ffffff"
#   footer_content: "#bfc9d3"

# Palette: https://palettes.shecodes.io/palettes/1313#palette
# colors:  
#   primary: "#385170" 
#   primary_rgb: "236,236,236" #rgb of the primary. Needed in some places for the transparency effect.
#   secondary: "#142d4c" 
#   link: "#385170"
#   link_hover: "#9fd3c7"
#   footer_heading: "#ffffff"
#   footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  # - title: dribbble
  #   url:
  # - title: facebook
  #   url:
  - title: twitter
    url: https://twitter.com/joannacss
  # - title: instagram
  #   url:
  # - title: tumblr
  #   url:
  - title: github
    url: https://github.com/s2e-lab/

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - University of Notre Dame
    - College of Engineering
    - 382 Fitzpatrick Hall
    - Notre Dame, IN 46556
email: jdasilv2@nd.edu
tel: (574) 631-0353


### GENERAL DATA FOR VARIOUS LOCATIONS ###



# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Security and Software Engineering Lab at University of Notre Dame, Notre Dame, IN USA 46556"

