### GENERAL SETTINGS ###

# Site settings
title: S2E Lab
description: "All about the Security and Software Engineering Lab at the University of Notre Dame!"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://s2e-lab.github.io"
github_username: s2e-lab
github_repo: s2e-lab.github.io

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is



# ORIGINAL TEMPLATE'S COLORS
# Palette: https://palettes.shecodes.io/palettes/267

colors:  
  primary: "#455d7a" 
  primary_rgb: "236,236,236" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#233142" 
  link: "#f95959"
  link_hover: "#e3e3e3"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Palette: https://palettes.shecodes.io/palettes/1313#palette
# colors:  
#   primary: "#385170" 
#   primary_rgb: "236,236,236" #rgb of the primary. Needed in some places for the transparency effect.
#   secondary: "#142d4c" 
#   link: "#385170"
#   link_hover: "#9fd3c7"
#   footer_heading: "#ffffff"
#   footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  # - title: dribbble
  #   url:
  # - title: facebook
  #   url:
  - title: twitter
    url: https://twitter.com/joannacss
  # - title: instagram
  #   url:
  # - title: tumblr
  #   url:
  - title: github
    url: https://github.com/s2e-lab/

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - University of Notre Dame
    - College of Engineering
    - 382 Fitzpatrick Hall
    - Notre Dame, IN 46556
email: jdasilv2@nd.edu
tel: (574) 631-0353


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
professors:
  - name: Joanna C. S. Santos
    position: Assistant Professor
    text: Computer Science and Engineering
    img: jdasilv2.jpg
    social:
      - title: linkedin #use for email address
        url: https://www.linkedin.com/in/joannacss/
    time: Fall 2021 - Present
        
graduates:
  - name: Beatrice Casey
    position: PhD Student
    text: Computer Science and Engineering
    img: bcasey6.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/beatrice-casey-4ab6aa1b2
    time: Aug. 2022 - Present
  - name: Vinicius Carvalho Lopes
    position: PhD Student
    text: Computer Science and Engineering
    img: vlopes.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/vinilopes03/
    time: Jan. 2022 - Present
  - name: Mohammed Latif Siddiq 
    position: PhD Student
    text: Computer Science and Engineering
    img: msiddiq3.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/lsiddiqsunny/
      - title: twitter
        url: https://twitter.com/lsiddiqsunny
      - title: globe
        url: https://lsiddiqsunny.github.io
    time: Jan. 2022 - Present
  
undergraduates:
  - name: Neol Gutierrez
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: ngutier4.jpg
    time: Spring 2024 - Present  
  - name: Sajith Devareddy
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: sdevared.jpg
    time: Spring 2024 - Present  
  - name: Andew Cotaj
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: acotaj.jpg
    time: Spring 2024 - Present  
  - name: Antonio Karam
    position: Undergraduate Student
    text: Computer Engineering
    org: ND
    img: akaram.jpg
    time: Spring 2024 - Present
  - name: Rena Steele
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: rsteele.jpg
    time: Spring 2024 - Present
  - name: Varun   Taneja
    position: Undergraduate Student
    text: Computer Engineering
    org: ND
    img: vtaneja.jpg
    time: Spring 2024 - Present
  - name: Maria C. Leal
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: mleal.jpg
    time: Spring 2024 - Present
  - name: Leyang Li
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: leyangli.jpg
    time: Spring 2024 - Present
  - name: Grace K. Odmark
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: godmark.jpg
    time: Spring 2024 - Present
    


alumni:
  - name: Luka Cvetko 
    position: MS Student
    text: Computer Science and Engineering
    img: lcvetko.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/luka-cvetko-649655162
    time: Jan. 2024 - May. 2024
    org: ND
  - name: Matthew Spadafore
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: mspadafo.jpg
    time: Jan. 2024 - May. 2024
  - name: Lindsay Roney
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: lroney.jpg
    time: Fall 2023 - Spring 2024  
  - name: Miguel Jose Maninang
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: mmaninan.jpg
    time: Jan. 2024 - May. 2024  
  - name: Claudia Kuczun
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: ckuczun.jpg
    time: Aug. 2023 - Dec. 2023
  - name: Jiahao Zhang
    position: Undergraduate Student
    text: Computer Science
    org: SUSTech
    img: jzhang.jpg
    time: Aug. 2023 - Dec. 2023
  - name: Anna Muller
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: amuller.jpg
    time: Fall 2023 - Fall 2023
  - name: Dan Krill
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: dkrill.jpg
    time: Fall 2023 - Fall 2023
  - name: Mark Rumsey
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: mrumsey.jpg
    time: Summer 2023 - Fall 2023
  - name: Eva Gorzkiewicz
    position: Undergraduate Student
    text: Computer Science
    img: egorzkie.jpg
    time: Summer 2023 - Fall 2023
  - name: George Perry
    position: Undergraduate Student
    text: Computer Science 
    org: ND
    img: gperry.jpg
    time: Fall 2022 - Fall 2023
  - name: Angel Ortiz
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: aortiz.jpeg
    time: Summer 2023
  - name: Emmanuel de La Paz
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: epaz.jpg
    time: Summer 2023
  - name: Desereé Frink-Larcart 
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: dfrinkla.jpg
    time: Spring 2023 - Spring 2023
  - name: Joshua Agron
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: jagron.jpg
    time: Fall 2021 - Spring 2022
  - name: Mark Cheng
    position: Undergraduate Student
    text: Computer Engineering
    org: ND
    img: mcheng3.jpg
    time: Spring 2022 - Spring 2022
  - name: Megan Campbell
    position: Undergraduate Student
    text: Computer Science
    org: ND
    img: mcambp24.jpg
    time: Fall 2021 - Fall 2021
visiting:
  - name: Ridwanul Hasan Tanvir
    position: Undergraduate Student
    text: Computer Science & Engineering
    org: BUET
    img: Ridwanul_Hasan_Tanvir.jpg
    time: Fall 2022-23 <span class="label label-default">Remote</span>
  - name: Simantika Dristi 
    position: Undergraduate Student 
    text: Computer Science & Engineering 
    org: BUET 
    img: dristi.jpg 
    time: Fall 2023 <span class="label label-default">Remote</span> 
  - name: Joy Saha 
    position: Undergraduate Student 
    text: Computer Science & Engineering 
    org: BUET 
    img: joy_saha.jpg 
    time: Fall 2023 <span class="label label-default">Remote</span>
  - name: Noshin Ulfat
    position: Undergraduate Student
    text: Computer Science & Engineering
    org: BUET
    img: ulfat.jpg
    time: Fall 2022 <span class="label label-default">Remote</span>
  - name: Fahmid Al Rifat
    position: Undergraduate Student
    text: Computer Science & Engineering
    org: BUET
    img: fahmid.jpg
    time: Fall 2022 <span class="label label-default">Remote</span>
  - name: Abdus Samee
    position: Undergraduate Student
    text: Computer Science & Engineering
    org: BUET
    img: samee.JPG
    time: Fall 2022 <span class="label label-default">Remote</span>
  - name: Sk Ruhul Azgor
    position: Undergraduate Student
    text: Computer Science & Engineering
    org: BUET
    img: ruhul.jpg
    time: Fall 2022 <span class="label label-default">Remote</span>
  - name: Md. Asif Haider
    position: Undergraduate Student
    text: Computer Science & Engineering
    org: BUET
    img: asif.jpg
    time: Fall 2022 <span class="label label-default">Remote</span>
  - name: Shehabul Islam Sawraz
    position: Undergraduate Student
    text: Computer Science & Engineering
    org: BUET
    img: sawraz.jpg
    time: Fall 2022 <span class="label label-default">Remote</span>
  - name: Shafayat Hossain Majumder
    position: Undergraduate Student
    text: Computer Science & Engineering
    org: BUET
    img: shafayat.jpg
    time: Summer 2022 <span class="label label-default">Remote</span>
  - name: Maisha Rahman Mim
    position: Undergraduate Student
    text: Computer Science & Engineering
    org: BUET
    img: maisha.png
    time: Summer 2022 <span class="label label-default">Remote</span>
  - name: Sourov Jajodia
    position: Undergraduate Student
    text: Computer Science & Engineering
    org: BUET
    img: sourov.png
    time: Summer 2022 <span class="label label-default">Remote</span>
  
mascots:
  - name: Atreus
    img: atreus.jpg
  - name: Kratos
    img: kratos.png
  - name: Pea
    img: pea.jpg
  - name: Nash
    img: nash.jpg
  - name: Ravan
    img: ravan.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Security and Software Engineering Lab at University of Notre Dame, Notre Dame, IN USA 46556"

