### GENERAL SETTINGS ###

# Site settings
title: S2E Lab
description: "All about the Security and Software Engineering Lab at the University of Notre Dame!"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://s2e-lab.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe"
  primary_rgb: "0, 178, 254" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#0c2340" #384452" 
  link: "#5aabbc"
  link_hover: "#f6e7a1"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url: joannacss
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - University of Notre Dame
    - College of Engineering
    - 382 Fitzpatrick Hall
    - Notre Dame, IN 46556
email: jdasilv2@nd.edu
tel: (574) 631-0353


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
professors:
  - name: Joanna C. S. Santos
    position: Assistant Professor
    text: Computer Science and Engineering
    img: jdasilv2.jpg
    social:
      - title: linkedin #use for email address
        url: https://www.linkedin.com/in/joannacss/
    time: Fall 2021 - Present
        
graduates:
  - name: Beatrice Casey
    position: PhD Student
    text: Computer Science and Engineering
    img: bcasey6.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/beatrice-casey-4ab6aa1b2
    time: Fall 2022 - Present
  - name: Mohammed Latif Siddiq 
    position: PhD Student
    text: Computer Science and Engineering
    img: msiddiq3.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/lsiddiqsunny/
      - title: twitter
        url: https://twitter.com/lsiddiqsunny
    time: Spring 2022 - Present
  - name: Vinicius Carvalho Lopes
    position: PhD Student
    text: Computer Science and Engineering
    img: vinicius.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/vinilopes03/
    time: Spring 2022 - Present
undergraduates:
alumni:
  - name: Joshua Agron
    position: Undergraduate Student
    text: Computer Science
    img: jagron.jpg
    social:
      - title: linkedin #use for email address
        url: https://www.linkedin.com/in/joshua-agron/
    time: Fall 2021 - Spring 2022
  - name: Mark Cheng
    position: Undergraduate Student
    text: Computer Engineering
    img: mcheng3.jpg
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/mark-cheng-6a9101189/
    time: Spring 2022 - Spring 2022
  - name: Megan Campbell
    position: Undergraduate Student
    text: Computer Science
    img: mcambp24.jpg
    social:
      - title: linkedin #use for email address
        url: https://www.linkedin.com/in/megan-campbell-nd2023/
    time: Fall 2021 - Fall 2021

# Clients information. Shown on Home and About pages. (Leftover from original, unnecessary?)
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Security and Software Engineering Lab at University of Notre Dame, Notre Dame, IN 46556"

# Testimonial content. Shown on Home and About page. (Leftover from original, unnecessary?)
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
